# Generated by Django 4.2 on 2023-05-06 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.menu_object', verbose_name='food'),
        ),
    ]
